# Generated by Django 3.2.4 on 2021-07-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_casno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='casno',
        ),
    ]
