# Generated by Django 3.2.4 on 2021-07-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_delete_casno'),
    ]

    operations = [
        migrations.CreateModel(
            name='casno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('NO', models.CharField(max_length=64)),
            ],
        ),
    ]
