# Generated by Django 3.2.4 on 2021-07-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_wafers'),
    ]

    operations = [
        migrations.CreateModel(
            name='gases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='labsupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='softwarelicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('bank', models.CharField(max_length=64)),
                ('accno', models.CharField(max_length=64)),
                ('route', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=64)),
            ],
        ),
    ]
