# Generated by Django 3.2.4 on 2021-07-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='compounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemicalformulla', models.CharField(max_length=64)),
                ('compoundname', models.CharField(max_length=64)),
                ('casrn', models.CharField(max_length=64)),
            ],
        ),
    ]
